#!/bin/bash

db_path="./databaseSystem"
mkdir -p "$db_path"
width=$(tput cols)
function printseparator {
    echo
    printf '%*s\n' "$width" '' | tr ' ' '='
    echo
}

function mainMenu
{
    clear
    printseparator
    printf "%*s%s\n" $(( $width/2 )) "Welcome to Database Manegment System"
    printseparator
    echo "1) Create Database"
    echo "2) List Databases"
    echo "3) Connect to Database"
    echo "4) Drop Database"
    echo "5) Exit"

    read -p "Choose an option: " choice

    case $choice in
        1)createdb ;;
        *)echo invalid
    esac
    
}


#START
mainMenu