#!/bin/bash

while true; do
    clear
    echo "===== MENU ====="
    echo "1. Show Date"
    echo "2. List Files"
    echo "3. Exit"
    echo "================"
    read -p "Choose an option [1-3]: " choice

    case $choice in
        1) date ;;
        2) ls ;;
        3) echo "Goodbye!"; break ;;
        *) echo "Invalid option!" ;;
    esac

    read -p "Press Enter to continue..."
done

